export const money = {
  name: "Money",
  children: [
    { name: "Ecosofische beginselen" },
    { name: "Flow money" },
    { name: "De centimeters zijn op" },
    { name: "De hoer, de boer, de slager, de waard en de toerist" },
    { name: "De rijken rijker en de armen rijken" },
    { name: "De rivier en haar identiteit" },
    { name: "Het elfde schijfje" },
    { name: "Gek Geld" },
    { name: "Serieus Gek Geld Spel" },
    { name: "Armillaria hoshin kanri" },
    { name: "Geld als rookgordijn" },
    { name: "Geld is een afspraak" },
    { name: "Geld voor een nieuwe samenleving" },
    { name: "Het geld van de toekomst" },
    { name: "Geld als instrument voor massaheling" },
    { name: "Heel onze Aarde met geld" },
    { name: "De toekomst van gratis" },
    { name: "Euros voor cybergeld wettig" },
    { name: "A flaw in the monetary system" },
    { name: "Direct, immediate exchange" },
    { name: "BitCoin explained" },
    { name: "Betaal met Arkel" },
    { name: "Betaal met belminuten" },
    { name: "Banken Bonus Battle" },
    { name: "Adembenemend geldsysteem" },
    { name: "Gouden ballen" },
    { name: "Als de dollar valt" },
    { name: "AEGON over renterot" },
    { name: "Fortis failliet" },
    { name: "Anthony stort zijn hart uit" },
  ],
};
export const community = {
  name: "Community",
  children: [
    { name: "Elke wijk in de stad is op zichzelf een stad" },
    { name: "Geschenkenconomie katalyseert gemeenschapszin" },
    { name: "Vriendkunst" },
    { name: "Holacratie" },
    { name: "Helping others makes us happy" },
    { name: "Duizend echte fans" },
    { name: "Aardnoot Wiki Marathon" },
    { name: "Aards paradijs" },
    { name: "Alliantie voor een nieuw mensdom" },
    { name: "Bewegende Beelden Festival 4 april" },
    { name: "Cogito en conscientia" },
    { name: "Creativity World Forum 2008" },
    { name: "Feedback van de deelgevers van het eerste uur" },
  ],
};
export const business = {
  name: "Business",
  children: [
    { name: "De toekomst van gratis" },
    { name: "Doorbraakversneller" },
    { name: "Hiepergroei" },
    { name: "Doorbreken in 7 stappen" },
    { name: "Made to stick" },
    { name: "Gun 50.000 euro aan je concurrent" },
    { name: "Change the changes" },
    { name: "De Essentie van Leiderschap" },
    { name: "Hoshin Kanri" },
    { name: "Hoshin Kanri Prezi" },
    { name: "How the markets really work" },
    { name: "Don’t eat the marshmallow yet" },
    { name: "De Tien Gezichten van Innovatie" },
    { name: "Gewoon…doen" },
  ],
};
export const develop = {
  name: "Develop",
  children: [
    { name: "Academie voor levenskunst" },
    { name: "Inhaalslag Bildung voor altijd" },
    { name: "Brad Neuberg on inventing with values" },
    { name: "Byron Katie" },
    { name: "Geluksbedrading standaard" },
  ],
};
export const spirit = {
  name: "Spirit",
  children: [
    { name: "De ziel van leiderschap" },
    { name: "Droom" },
    { name: "En ik dan" },
    { name: "Deepak Chopra in Almere op 16 april" },
    { name: "Deepak Chopra in Nederland" },
    { name: "The soul hypothesis" },
    { name: "Beleving van verbinding" },
    { name: "Bericht uit het Universum" },
    { name: "Daniel Goleman over compassie" },
    { name: "De wereld van Merlijn" },
    { name: "Geurt Busser, waddenschilder" },
    { name: "Gandhi Nederland Tour" },
  ],
};
export const identity = {
  name: "Identity",
  children: [{ name: "Aardbron Moodboard" }],
};
export const aardbron = {
  name: "Aardbron",
  open: true,
  children: [money, community, business, develop, spirit, identity],
};
