export const geld = {
  name: "Geld",
  children: [
    { name: "Ecosofische beginselen" },
    { name: "De centimeters zijn op" },
    { name: "Onmogelijke hamster" },
    { name: "De hoer, de boer, de slager, de waard en de toerist" },
    { name: "De rijken rijker en de armen rijken" },
    { name: "Huidig geldsysteem onwettig" },
    { name: "Op zoek naar een nieuw idee van ‘geld’" },
    { name: "De rivier en haar identiteit" },
    { name: "Het elfde schijfje" },
    { name: "Gek Geld" },
    { name: "Serieus Gek Geld Spel" },
    { name: "Armillaria hoshin kanri" },
    { name: "Geld als rookgordijn" },
    { name: "Geld is een afspraak" },
    { name: "Geld voor een nieuwe samenleving" },
    { name: "Het geld van de toekomst" },
    { name: "Geld als instrument voor massaheling" },
    { name: "Invoering van ecogeld" },
    { name: "Heel onze Aarde met geld" },
    { name: "De toekomst van gratis" },
    { name: "Euros voor cybergeld wettig" },
    { name: "Mensen willen graag betalen" },
    { name: "Medeleven met Madoff" },
    { name: "Betaal met Arkel" },
    { name: "Betaal met belminuten" },
    { name: "Banken Bonus Battle" },
    { name: "Adembenemend geldsysteem" },
    { name: "Gouden ballen" },
    { name: "Als de dollar valt" },
    { name: "Miljardairs 50 procent rijker in 2009" },
    { name: "AEGON over renterot" },
    { name: "Fortis failliet" },
    { name: "Anthony stort zijn hart uit" },
  ],
};
export const money = {
  name: "Money",
  children: [
    { name: "Flow money" },
    { name: "Money as the instrument of mass healing" },
    { name: "A flaw in the monetary system" },
    { name: "Money malfunction, and what we can do about it" },
    { name: "Direct, immediate exchange" },
    { name: "Kredietcrisis left & right" },
    { name: "BitCoin explained" },
  ],
};
export const community = {
  name: "Community",
  children: [
    { name: "Levende organisaties" },
    { name: "Metamorfose" },
    { name: "Elke wijk in de stad is op zichzelf een stad" },
    { name: "Geschenkenconomie katalyseert gemeenschapszin" },
    { name: "Vriendkunst" },
    { name: "Holacratie" },
    { name: "Helping others makes us happy" },
    { name: "Howard Rheingold over samenwerken" },
    { name: "Duizend echte fans" },
    { name: "Aardnoot Wiki Marathon" },
    { name: "Aards paradijs" },
    { name: "Alliantie voor een nieuw mensdom" },
    { name: "Monsterlijke mensen" },
    { name: "Bewegende Beelden Festival 4 april" },
    { name: "Cogito en conscientia" },
    { name: "Creativity World Forum 2008" },
    { name: "Nomads Life" },
    { name: "Feedback van de deelgevers van het eerste uur" },
  ],
};
export const business = {
  name: "Business",
  children: [
    { name: "De toekomst van gratis" },
    { name: "Doorbraakversneller" },
    { name: "JAM School over Visueel Denken" },
    { name: "JAM in het Co-creation lab" },
    { name: "Hiepergroei" },
    { name: "Doorbreken in 7 stappen" },
    { name: "Kwispel de Langstaart der Liefde" },
    { name: "John Cleese over creativiteit" },
    { name: "Koe en Paardebloem" },
    { name: "Innoveer je bedrijfsmodel" },
    { name: "Made to stick" },
    { name: "Gun 50.000 euro aan je concurrent" },
    { name: "Change the changes" },
    { name: "Hoshin Kanri" },
    { name: "Hoshin Kanri Prezi" },
    { name: "How the markets really work" },
    { name: "Don’t eat the marshmallow yet" },
    { name: "De Tien Gezichten van Innovatie" },
    { name: "Gewoon…doen" },
    { name: "Open enterprise" },
  ],
};
export const develop = {
  name: "Develop",
  children: [
    { name: "Academie voor levenskunst" },
    { name: "Levende systemen" },
    { name: "Inhaalslag Bildung voor altijd" },
    { name: "Hypercortex" },
    { name: "Brad Neuberg on inventing with values" },
    { name: "Byron Katie" },
    { name: "J.K. Rowling over falen en verbeelden" },
    { name: "Geluksbedrading standaard" },
    { name: "Innovatieplatform Noord-Nederland" },
  ],
};
export const leiderschap = {
  name: "Leiderschap",
  children: [
    { name: "De Essentie van Leiderschap" },
    { name: "Leiderschap ben je zelf" },
    { name: "Margaret Wheatley over duurzaam leidinggeven" },
    { name: "De ziel van leiderschap" },
  ],
};
export const spirit = {
  name: "Spirit",
  children: [
    { name: "Droom" },
    { name: "Open geest" },
    { name: "Love, The Purest Form of Energy" },
    { name: "Op slag inzicht" },
    { name: "En ik dan" },
    { name: "Leven is een kunst om te leren" },
    { name: "Noösfeer" },
    { name: "Living is an art to be learned" },
    { name: "Deepak Chopra in Almere op 16 april" },
    { name: "Deepak Chopra in Nederland" },
    { name: "Mijn intentie" },
    { name: "The soul hypothesis" },
    { name: "Beleving van verbinding" },
    { name: "Bericht uit het Universum" },
    { name: "Daniel Goleman over compassie" },
    { name: "De wereld van Merlijn" },
    { name: "Geurt Busser, waddenschilder" },
    { name: "Gandhi Nederland Tour" },
    { name: "Mens en Spirit" },
  ],
};
export const identity = {
  name: "Identity",
  children: [{ name: "Aardbron Moodboard" }],
};
export const aardbron = {
  name: "Aardbron",
  open: true,
  children: [
    geld,
    money,
    develop,
    leiderschap,
    community,
    business,
    spirit,
    identity,
  ],
};
